/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_silveregg_wrapper_WrapperManager */

#ifndef _Included_com_silveregg_wrapper_WrapperManager
#define _Included_com_silveregg_wrapper_WrapperManager
#ifdef __cplusplus
extern "C" {
#endif
#undef com_silveregg_wrapper_WrapperManager_DEFAULT_PORT
#define com_silveregg_wrapper_WrapperManager_DEFAULT_PORT 15003L
#undef com_silveregg_wrapper_WrapperManager_DEFAULT_BACKLOG
#define com_silveregg_wrapper_WrapperManager_DEFAULT_BACKLOG 50L
#undef com_silveregg_wrapper_WrapperManager_DEFAULT_TIMEOUT
#define com_silveregg_wrapper_WrapperManager_DEFAULT_TIMEOUT 10L
#undef com_silveregg_wrapper_WrapperManager_WRAPPER_MSG_START
#define com_silveregg_wrapper_WrapperManager_WRAPPER_MSG_START 100L
#undef com_silveregg_wrapper_WrapperManager_WRAPPER_MSG_STOP
#define com_silveregg_wrapper_WrapperManager_WRAPPER_MSG_STOP 101L
#undef com_silveregg_wrapper_WrapperManager_WRAPPER_MSG_RESTART
#define com_silveregg_wrapper_WrapperManager_WRAPPER_MSG_RESTART 102L
#undef com_silveregg_wrapper_WrapperManager_WRAPPER_MSG_PING
#define com_silveregg_wrapper_WrapperManager_WRAPPER_MSG_PING 103L
#undef com_silveregg_wrapper_WrapperManager_WRAPPER_MSG_STOP_PENDING
#define com_silveregg_wrapper_WrapperManager_WRAPPER_MSG_STOP_PENDING 104L
#undef com_silveregg_wrapper_WrapperManager_WRAPPER_MSG_START_PENDING
#define com_silveregg_wrapper_WrapperManager_WRAPPER_MSG_START_PENDING 105L
#undef com_silveregg_wrapper_WrapperManager_WRAPPER_MSG_STARTED
#define com_silveregg_wrapper_WrapperManager_WRAPPER_MSG_STARTED 106L
#undef com_silveregg_wrapper_WrapperManager_WRAPPER_MSG_STOPPED
#define com_silveregg_wrapper_WrapperManager_WRAPPER_MSG_STOPPED 107L
#undef com_silveregg_wrapper_WrapperManager_WRAPPER_MSG_KEY
#define com_silveregg_wrapper_WrapperManager_WRAPPER_MSG_KEY 110L
#undef com_silveregg_wrapper_WrapperManager_WRAPPER_MSG_BADKEY
#define com_silveregg_wrapper_WrapperManager_WRAPPER_MSG_BADKEY 111L
#undef com_silveregg_wrapper_WrapperManager_WRAPPER_CTRL_C_EVENT
#define com_silveregg_wrapper_WrapperManager_WRAPPER_CTRL_C_EVENT 200L
#undef com_silveregg_wrapper_WrapperManager_WRAPPER_CTRL_CLOSE_EVENT
#define com_silveregg_wrapper_WrapperManager_WRAPPER_CTRL_CLOSE_EVENT 201L
#undef com_silveregg_wrapper_WrapperManager_WRAPPER_CTRL_LOGOFF_EVENT
#define com_silveregg_wrapper_WrapperManager_WRAPPER_CTRL_LOGOFF_EVENT 202L
#undef com_silveregg_wrapper_WrapperManager_WRAPPER_CTRL_SHUTDOWN_EVENT
#define com_silveregg_wrapper_WrapperManager_WRAPPER_CTRL_SHUTDOWN_EVENT 203L
/* Inaccessible static: _disposed */
/* Inaccessible static: _started */
/* Inaccessible static: _instance */
/* Inaccessible static: _hook */
/* Inaccessible static: _hookTriggered */
/* Inaccessible static: _args */
/* Inaccessible static: _port */
/* Inaccessible static: _key */
/* Inaccessible static: _timeout */
/* Inaccessible static: _backlog */
/* Inaccessible static: _runner */
/* Inaccessible static: _eventRunner */
/* Inaccessible static: _listener */
/* Inaccessible static: _lastPing */
/* Inaccessible static: _serverSocket */
/* Inaccessible static: _socket */
/* Inaccessible static: _shuttingDown */
/* Inaccessible static: _appearHung */
/* Inaccessible static: _service */
/* Inaccessible static: _debug */
/* Inaccessible static: _jvmId */
/* Inaccessible static: _stopping */
/* Inaccessible static: _libraryOK */
/* Inaccessible static: _commandBuffer */
/* Inaccessible static: _res */
/* Inaccessible static: _error */
/* Inaccessible static: _warning */
/* Inaccessible static: _info */
/*
 * Class:     com_silveregg_wrapper_WrapperManager
 * Method:    nativeInit
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_silveregg_wrapper_WrapperManager_nativeInit
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_silveregg_wrapper_WrapperManager
 * Method:    nativeGetControlEvent
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_silveregg_wrapper_WrapperManager_nativeGetControlEvent
  (JNIEnv *, jclass);

/*
 * Class:     com_silveregg_wrapper_WrapperManager
 * Method:    accessViolationInner
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_silveregg_wrapper_WrapperManager_accessViolationInner
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
