/*
 * Copyright (c) 2001 Silver Egg Technology
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without 
 * restriction, including without limitation the rights to use, 
 * copy, modify, merge, publish, distribute, sublicense, and/or 
 * sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following 
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, 
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES 
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND 
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

// $Log$
// Revision 1.2  2001/11/08 04:22:28  mortenson
// Had been having a problem with the windows build where the WIN32
// symbol was not defined sometimes.  Figured out that that was the
// cause of a strange build problem enabling me to remove the
// workaround code.  wrapperjni_win.c will now fail to build if the symbol
// is not defined.
//
// Revision 1.1.1.1  2001/11/07 08:54:20  mortenson
// no message
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_silveregg_wrapper_WrapperManager */

#ifndef _Included_com_silveregg_wrapper_WrapperManager
#define _Included_com_silveregg_wrapper_WrapperManager
#ifdef __cplusplus
extern "C" {
#endif

#undef com_silveregg_wrapper_WrapperManager_WRAPPER_CTRL_C_EVENT
#define com_silveregg_wrapper_WrapperManager_WRAPPER_CTRL_C_EVENT 200L
#undef com_silveregg_wrapper_WrapperManager_WRAPPER_CTRL_CLOSE_EVENT
#define com_silveregg_wrapper_WrapperManager_WRAPPER_CTRL_CLOSE_EVENT 201L
#undef com_silveregg_wrapper_WrapperManager_WRAPPER_CTRL_LOGOFF_EVENT
#define com_silveregg_wrapper_WrapperManager_WRAPPER_CTRL_LOGOFF_EVENT 202L
#undef com_silveregg_wrapper_WrapperManager_WRAPPER_CTRL_SHUTDOWN_EVENT
#define com_silveregg_wrapper_WrapperManager_WRAPPER_CTRL_SHUTDOWN_EVENT 203L

/*
 * Class:     com_silveregg_wrapper_WrapperManager
 * Method:    nativeInit
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_silveregg_wrapper_WrapperManager_nativeInit
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_silveregg_wrapper_WrapperManager
 * Method:    nativeGetControlEvent
 * Signature: (V)I
 */
JNIEXPORT int JNICALL Java_com_silveregg_wrapper_WrapperManager_nativeGetControlEvent
  (JNIEnv *, jclass);

/*
 * Class:     com_silveregg_wrapper_WrapperManager
 * Method:    accessViolationInner
 * Signature: (V)V
 */
JNIEXPORT void JNICALL Java_com_silveregg_wrapper_WrapperManager_accessViolationInner
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
